// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsMessages(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsMessages(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsMessages(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashMessages(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashMessages(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashMessages(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

enum CameraUpdateType: Int {
  case newCameraPosition = 0
  case newLatLng = 1
  case newLatLngZoom = 2
  case newLatLngBounds = 3
  case zoomBy = 4
  case zoomTo = 5
  case zoomIn = 6
  case zoomOut = 7
}

enum BitmapDescriptorType: Int {
  case defaultAnnotation = 0
  case markerAnnotation = 1
  case fromAssetImage = 2
  case fromBytes = 3
}

enum CapType: Int {
  case buttCap = 0
  case roundCap = 1
  case squareCap = 2
}

enum PatternItemType: Int {
  case dot = 0
  case dash = 1
  case gap = 2
}

/// Emphasis style for the standard map configuration (iOS 16+).
enum PlatformMapEmphasisStyle: Int {
  /// The default map appearance.
  case defaultStyle = 0
  /// A muted appearance that de-emphasises labels and icons.
  case muted = 1
}

/// The type of a built-in map feature tapped by the user (iOS 16+).
enum PlatformMapFeatureType: Int {
  case pointOfInterest = 0
  case territory = 1
  case physicalFeature = 2
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformOffset: Hashable {
  var x: Double
  var y: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformOffset? {
    let x = pigeonVar_list[0] as! Double
    let y = pigeonVar_list[1] as! Double

    return PlatformOffset(
      x: x,
      y: y
    )
  }
  func toList() -> [Any?] {
    return [
      x,
      y,
    ]
  }
  static func == (lhs: PlatformOffset, rhs: PlatformOffset) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformLatLng: Hashable {
  var latitude: Double
  var longitude: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformLatLng? {
    let latitude = pigeonVar_list[0] as! Double
    let longitude = pigeonVar_list[1] as! Double

    return PlatformLatLng(
      latitude: latitude,
      longitude: longitude
    )
  }
  func toList() -> [Any?] {
    return [
      latitude,
      longitude,
    ]
  }
  static func == (lhs: PlatformLatLng, rhs: PlatformLatLng) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformLatLngBounds: Hashable {
  var southwest: PlatformLatLng
  var northeast: PlatformLatLng


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformLatLngBounds? {
    let southwest = pigeonVar_list[0] as! PlatformLatLng
    let northeast = pigeonVar_list[1] as! PlatformLatLng

    return PlatformLatLngBounds(
      southwest: southwest,
      northeast: northeast
    )
  }
  func toList() -> [Any?] {
    return [
      southwest,
      northeast,
    ]
  }
  static func == (lhs: PlatformLatLngBounds, rhs: PlatformLatLngBounds) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformScreenCoordinate: Hashable {
  var x: Double
  var y: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformScreenCoordinate? {
    let x = pigeonVar_list[0] as! Double
    let y = pigeonVar_list[1] as! Double

    return PlatformScreenCoordinate(
      x: x,
      y: y
    )
  }
  func toList() -> [Any?] {
    return [
      x,
      y,
    ]
  }
  static func == (lhs: PlatformScreenCoordinate, rhs: PlatformScreenCoordinate) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformCameraPosition: Hashable {
  var target: PlatformLatLng
  var heading: Double
  var pitch: Double
  var zoom: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformCameraPosition? {
    let target = pigeonVar_list[0] as! PlatformLatLng
    let heading = pigeonVar_list[1] as! Double
    let pitch = pigeonVar_list[2] as! Double
    let zoom = pigeonVar_list[3] as! Double

    return PlatformCameraPosition(
      target: target,
      heading: heading,
      pitch: pitch,
      zoom: zoom
    )
  }
  func toList() -> [Any?] {
    return [
      target,
      heading,
      pitch,
      zoom,
    ]
  }
  static func == (lhs: PlatformCameraPosition, rhs: PlatformCameraPosition) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformMinMaxZoomPreference: Hashable {
  var minZoom: Double? = nil
  var maxZoom: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformMinMaxZoomPreference? {
    let minZoom: Double? = nilOrValue(pigeonVar_list[0])
    let maxZoom: Double? = nilOrValue(pigeonVar_list[1])

    return PlatformMinMaxZoomPreference(
      minZoom: minZoom,
      maxZoom: maxZoom
    )
  }
  func toList() -> [Any?] {
    return [
      minZoom,
      maxZoom,
    ]
  }
  static func == (lhs: PlatformMinMaxZoomPreference, rhs: PlatformMinMaxZoomPreference) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformPadding: Hashable {
  var top: Double
  var left: Double
  var bottom: Double
  var right: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformPadding? {
    let top = pigeonVar_list[0] as! Double
    let left = pigeonVar_list[1] as! Double
    let bottom = pigeonVar_list[2] as! Double
    let right = pigeonVar_list[3] as! Double

    return PlatformPadding(
      top: top,
      left: left,
      bottom: bottom,
      right: right
    )
  }
  func toList() -> [Any?] {
    return [
      top,
      left,
      bottom,
      right,
    ]
  }
  static func == (lhs: PlatformPadding, rhs: PlatformPadding) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformCameraTargetBounds: Hashable {
  var bounds: PlatformLatLngBounds? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformCameraTargetBounds? {
    let bounds: PlatformLatLngBounds? = nilOrValue(pigeonVar_list[0])

    return PlatformCameraTargetBounds(
      bounds: bounds
    )
  }
  func toList() -> [Any?] {
    return [
      bounds
    ]
  }
  static func == (lhs: PlatformCameraTargetBounds, rhs: PlatformCameraTargetBounds) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// A built-in map feature (e.g. POI, landmark) selected by the user (iOS 16+).
///
/// Generated class from Pigeon that represents data sent in messages.
struct PlatformMapFeature: Hashable {
  var coordinate: PlatformLatLng
  var featureType: PlatformMapFeatureType
  /// The display title of the feature, if available.
  var title: String? = nil
  /// The raw `MKPointOfInterestCategory` string value for `.pointOfInterest`
  /// features, e.g. `"MKPOICategoryRestaurant"`. Null for other feature types.
  var pointOfInterestCategory: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformMapFeature? {
    let coordinate = pigeonVar_list[0] as! PlatformLatLng
    let featureType = pigeonVar_list[1] as! PlatformMapFeatureType
    let title: String? = nilOrValue(pigeonVar_list[2])
    let pointOfInterestCategory: String? = nilOrValue(pigeonVar_list[3])

    return PlatformMapFeature(
      coordinate: coordinate,
      featureType: featureType,
      title: title,
      pointOfInterestCategory: pointOfInterestCategory
    )
  }
  func toList() -> [Any?] {
    return [
      coordinate,
      featureType,
      title,
      pointOfInterestCategory,
    ]
  }
  static func == (lhs: PlatformMapFeature, rhs: PlatformMapFeature) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformMapOptions: Hashable {
  var compassEnabled: Bool? = nil
  var trafficEnabled: Bool? = nil
  var mapType: Int64? = nil
  var minMaxZoomPreference: PlatformMinMaxZoomPreference? = nil
  var rotateGesturesEnabled: Bool? = nil
  var scrollGesturesEnabled: Bool? = nil
  var pitchGesturesEnabled: Bool? = nil
  var trackingMode: Int64? = nil
  var zoomGesturesEnabled: Bool? = nil
  var myLocationEnabled: Bool? = nil
  var myLocationButtonEnabled: Bool? = nil
  var padding: PlatformPadding? = nil
  var insetsLayoutMarginsFromSafeArea: Bool? = nil
  var cameraTargetBounds: PlatformCameraTargetBounds? = nil
  var buildingsEnabled: Bool? = nil
  var pointsOfInterestEnabled: Bool? = nil
  var scaleEnabled: Bool? = nil
  /// Emphasis style for the standard map (iOS 16+, no-op on other map types).
  var emphasisStyle: PlatformMapEmphasisStyle? = nil
  /// Bitmask of selectable built-in map features (iOS 16+).
  /// Bit 0 = pointsOfInterest, bit 1 = territories, bit 2 = physicalFeatures.
  var selectableFeatures: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformMapOptions? {
    let compassEnabled: Bool? = nilOrValue(pigeonVar_list[0])
    let trafficEnabled: Bool? = nilOrValue(pigeonVar_list[1])
    let mapType: Int64? = nilOrValue(pigeonVar_list[2])
    let minMaxZoomPreference: PlatformMinMaxZoomPreference? = nilOrValue(pigeonVar_list[3])
    let rotateGesturesEnabled: Bool? = nilOrValue(pigeonVar_list[4])
    let scrollGesturesEnabled: Bool? = nilOrValue(pigeonVar_list[5])
    let pitchGesturesEnabled: Bool? = nilOrValue(pigeonVar_list[6])
    let trackingMode: Int64? = nilOrValue(pigeonVar_list[7])
    let zoomGesturesEnabled: Bool? = nilOrValue(pigeonVar_list[8])
    let myLocationEnabled: Bool? = nilOrValue(pigeonVar_list[9])
    let myLocationButtonEnabled: Bool? = nilOrValue(pigeonVar_list[10])
    let padding: PlatformPadding? = nilOrValue(pigeonVar_list[11])
    let insetsLayoutMarginsFromSafeArea: Bool? = nilOrValue(pigeonVar_list[12])
    let cameraTargetBounds: PlatformCameraTargetBounds? = nilOrValue(pigeonVar_list[13])
    let buildingsEnabled: Bool? = nilOrValue(pigeonVar_list[14])
    let pointsOfInterestEnabled: Bool? = nilOrValue(pigeonVar_list[15])
    let scaleEnabled: Bool? = nilOrValue(pigeonVar_list[16])
    let emphasisStyle: PlatformMapEmphasisStyle? = nilOrValue(pigeonVar_list[17])
    let selectableFeatures: Int64? = nilOrValue(pigeonVar_list[18])

    return PlatformMapOptions(
      compassEnabled: compassEnabled,
      trafficEnabled: trafficEnabled,
      mapType: mapType,
      minMaxZoomPreference: minMaxZoomPreference,
      rotateGesturesEnabled: rotateGesturesEnabled,
      scrollGesturesEnabled: scrollGesturesEnabled,
      pitchGesturesEnabled: pitchGesturesEnabled,
      trackingMode: trackingMode,
      zoomGesturesEnabled: zoomGesturesEnabled,
      myLocationEnabled: myLocationEnabled,
      myLocationButtonEnabled: myLocationButtonEnabled,
      padding: padding,
      insetsLayoutMarginsFromSafeArea: insetsLayoutMarginsFromSafeArea,
      cameraTargetBounds: cameraTargetBounds,
      buildingsEnabled: buildingsEnabled,
      pointsOfInterestEnabled: pointsOfInterestEnabled,
      scaleEnabled: scaleEnabled,
      emphasisStyle: emphasisStyle,
      selectableFeatures: selectableFeatures
    )
  }
  func toList() -> [Any?] {
    return [
      compassEnabled,
      trafficEnabled,
      mapType,
      minMaxZoomPreference,
      rotateGesturesEnabled,
      scrollGesturesEnabled,
      pitchGesturesEnabled,
      trackingMode,
      zoomGesturesEnabled,
      myLocationEnabled,
      myLocationButtonEnabled,
      padding,
      insetsLayoutMarginsFromSafeArea,
      cameraTargetBounds,
      buildingsEnabled,
      pointsOfInterestEnabled,
      scaleEnabled,
      emphasisStyle,
      selectableFeatures,
    ]
  }
  static func == (lhs: PlatformMapOptions, rhs: PlatformMapOptions) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformInfoWindow: Hashable {
  var title: String? = nil
  var snippet: String? = nil
  var anchor: PlatformOffset? = nil
  var consumesTapEvents: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformInfoWindow? {
    let title: String? = nilOrValue(pigeonVar_list[0])
    let snippet: String? = nilOrValue(pigeonVar_list[1])
    let anchor: PlatformOffset? = nilOrValue(pigeonVar_list[2])
    let consumesTapEvents = pigeonVar_list[3] as! Bool

    return PlatformInfoWindow(
      title: title,
      snippet: snippet,
      anchor: anchor,
      consumesTapEvents: consumesTapEvents
    )
  }
  func toList() -> [Any?] {
    return [
      title,
      snippet,
      anchor,
      consumesTapEvents,
    ]
  }
  static func == (lhs: PlatformInfoWindow, rhs: PlatformInfoWindow) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformBitmapDescriptor: Hashable {
  var type: BitmapDescriptorType
  var hue: Double? = nil
  var assetName: String? = nil
  var assetScale: Double? = nil
  var bytes: FlutterStandardTypedData? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformBitmapDescriptor? {
    let type = pigeonVar_list[0] as! BitmapDescriptorType
    let hue: Double? = nilOrValue(pigeonVar_list[1])
    let assetName: String? = nilOrValue(pigeonVar_list[2])
    let assetScale: Double? = nilOrValue(pigeonVar_list[3])
    let bytes: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[4])

    return PlatformBitmapDescriptor(
      type: type,
      hue: hue,
      assetName: assetName,
      assetScale: assetScale,
      bytes: bytes
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      hue,
      assetName,
      assetScale,
      bytes,
    ]
  }
  static func == (lhs: PlatformBitmapDescriptor, rhs: PlatformBitmapDescriptor) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformAnnotation: Hashable {
  var annotationId: String
  var alpha: Double
  var anchor: PlatformOffset
  var draggable: Bool
  var icon: PlatformBitmapDescriptor
  var infoWindow: PlatformInfoWindow
  var visible: Bool
  var position: PlatformLatLng
  var zIndex: Double
  /// When set, annotations with the same identifier are eligible for clustering.
  /// Maps to MKAnnotationView.clusteringIdentifier on iOS 11+.
  var clusteringIdentifier: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformAnnotation? {
    let annotationId = pigeonVar_list[0] as! String
    let alpha = pigeonVar_list[1] as! Double
    let anchor = pigeonVar_list[2] as! PlatformOffset
    let draggable = pigeonVar_list[3] as! Bool
    let icon = pigeonVar_list[4] as! PlatformBitmapDescriptor
    let infoWindow = pigeonVar_list[5] as! PlatformInfoWindow
    let visible = pigeonVar_list[6] as! Bool
    let position = pigeonVar_list[7] as! PlatformLatLng
    let zIndex = pigeonVar_list[8] as! Double
    let clusteringIdentifier: String? = nilOrValue(pigeonVar_list[9])

    return PlatformAnnotation(
      annotationId: annotationId,
      alpha: alpha,
      anchor: anchor,
      draggable: draggable,
      icon: icon,
      infoWindow: infoWindow,
      visible: visible,
      position: position,
      zIndex: zIndex,
      clusteringIdentifier: clusteringIdentifier
    )
  }
  func toList() -> [Any?] {
    return [
      annotationId,
      alpha,
      anchor,
      draggable,
      icon,
      infoWindow,
      visible,
      position,
      zIndex,
      clusteringIdentifier,
    ]
  }
  static func == (lhs: PlatformAnnotation, rhs: PlatformAnnotation) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformAnnotationUpdates: Hashable {
  var annotationsToAdd: [PlatformAnnotation]? = nil
  var annotationsToChange: [PlatformAnnotation]? = nil
  var annotationIdsToRemove: [String]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformAnnotationUpdates? {
    let annotationsToAdd: [PlatformAnnotation]? = nilOrValue(pigeonVar_list[0])
    let annotationsToChange: [PlatformAnnotation]? = nilOrValue(pigeonVar_list[1])
    let annotationIdsToRemove: [String]? = nilOrValue(pigeonVar_list[2])

    return PlatformAnnotationUpdates(
      annotationsToAdd: annotationsToAdd,
      annotationsToChange: annotationsToChange,
      annotationIdsToRemove: annotationIdsToRemove
    )
  }
  func toList() -> [Any?] {
    return [
      annotationsToAdd,
      annotationsToChange,
      annotationIdsToRemove,
    ]
  }
  static func == (lhs: PlatformAnnotationUpdates, rhs: PlatformAnnotationUpdates) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformPatternItem: Hashable {
  var type: PatternItemType
  var length: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformPatternItem? {
    let type = pigeonVar_list[0] as! PatternItemType
    let length: Double? = nilOrValue(pigeonVar_list[1])

    return PlatformPatternItem(
      type: type,
      length: length
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      length,
    ]
  }
  static func == (lhs: PlatformPatternItem, rhs: PlatformPatternItem) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformPolyline: Hashable {
  var polylineId: String
  var consumeTapEvents: Bool
  var color: Int64
  var polylineCap: CapType
  var jointType: Int64
  var visible: Bool
  var width: Int64
  var zIndex: Int64? = nil
  var points: [PlatformLatLng]
  var patterns: [PlatformPatternItem]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformPolyline? {
    let polylineId = pigeonVar_list[0] as! String
    let consumeTapEvents = pigeonVar_list[1] as! Bool
    let color = pigeonVar_list[2] as! Int64
    let polylineCap = pigeonVar_list[3] as! CapType
    let jointType = pigeonVar_list[4] as! Int64
    let visible = pigeonVar_list[5] as! Bool
    let width = pigeonVar_list[6] as! Int64
    let zIndex: Int64? = nilOrValue(pigeonVar_list[7])
    let points = pigeonVar_list[8] as! [PlatformLatLng]
    let patterns = pigeonVar_list[9] as! [PlatformPatternItem]

    return PlatformPolyline(
      polylineId: polylineId,
      consumeTapEvents: consumeTapEvents,
      color: color,
      polylineCap: polylineCap,
      jointType: jointType,
      visible: visible,
      width: width,
      zIndex: zIndex,
      points: points,
      patterns: patterns
    )
  }
  func toList() -> [Any?] {
    return [
      polylineId,
      consumeTapEvents,
      color,
      polylineCap,
      jointType,
      visible,
      width,
      zIndex,
      points,
      patterns,
    ]
  }
  static func == (lhs: PlatformPolyline, rhs: PlatformPolyline) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformPolylineUpdates: Hashable {
  var polylinesToAdd: [PlatformPolyline]? = nil
  var polylinesToChange: [PlatformPolyline]? = nil
  var polylineIdsToRemove: [String]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformPolylineUpdates? {
    let polylinesToAdd: [PlatformPolyline]? = nilOrValue(pigeonVar_list[0])
    let polylinesToChange: [PlatformPolyline]? = nilOrValue(pigeonVar_list[1])
    let polylineIdsToRemove: [String]? = nilOrValue(pigeonVar_list[2])

    return PlatformPolylineUpdates(
      polylinesToAdd: polylinesToAdd,
      polylinesToChange: polylinesToChange,
      polylineIdsToRemove: polylineIdsToRemove
    )
  }
  func toList() -> [Any?] {
    return [
      polylinesToAdd,
      polylinesToChange,
      polylineIdsToRemove,
    ]
  }
  static func == (lhs: PlatformPolylineUpdates, rhs: PlatformPolylineUpdates) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformPolygon: Hashable {
  var polygonId: String
  var consumeTapEvents: Bool
  var fillColor: Int64
  var points: [PlatformLatLng]
  var strokeColor: Int64
  var strokeWidth: Int64
  var visible: Bool
  var zIndex: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformPolygon? {
    let polygonId = pigeonVar_list[0] as! String
    let consumeTapEvents = pigeonVar_list[1] as! Bool
    let fillColor = pigeonVar_list[2] as! Int64
    let points = pigeonVar_list[3] as! [PlatformLatLng]
    let strokeColor = pigeonVar_list[4] as! Int64
    let strokeWidth = pigeonVar_list[5] as! Int64
    let visible = pigeonVar_list[6] as! Bool
    let zIndex: Int64? = nilOrValue(pigeonVar_list[7])

    return PlatformPolygon(
      polygonId: polygonId,
      consumeTapEvents: consumeTapEvents,
      fillColor: fillColor,
      points: points,
      strokeColor: strokeColor,
      strokeWidth: strokeWidth,
      visible: visible,
      zIndex: zIndex
    )
  }
  func toList() -> [Any?] {
    return [
      polygonId,
      consumeTapEvents,
      fillColor,
      points,
      strokeColor,
      strokeWidth,
      visible,
      zIndex,
    ]
  }
  static func == (lhs: PlatformPolygon, rhs: PlatformPolygon) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformPolygonUpdates: Hashable {
  var polygonsToAdd: [PlatformPolygon]? = nil
  var polygonsToChange: [PlatformPolygon]? = nil
  var polygonIdsToRemove: [String]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformPolygonUpdates? {
    let polygonsToAdd: [PlatformPolygon]? = nilOrValue(pigeonVar_list[0])
    let polygonsToChange: [PlatformPolygon]? = nilOrValue(pigeonVar_list[1])
    let polygonIdsToRemove: [String]? = nilOrValue(pigeonVar_list[2])

    return PlatformPolygonUpdates(
      polygonsToAdd: polygonsToAdd,
      polygonsToChange: polygonsToChange,
      polygonIdsToRemove: polygonIdsToRemove
    )
  }
  func toList() -> [Any?] {
    return [
      polygonsToAdd,
      polygonsToChange,
      polygonIdsToRemove,
    ]
  }
  static func == (lhs: PlatformPolygonUpdates, rhs: PlatformPolygonUpdates) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformCircle: Hashable {
  var circleId: String
  var consumeTapEvents: Bool
  var fillColor: Int64
  var center: PlatformLatLng
  var radius: Double
  var strokeColor: Int64
  var strokeWidth: Int64
  var visible: Bool
  var zIndex: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformCircle? {
    let circleId = pigeonVar_list[0] as! String
    let consumeTapEvents = pigeonVar_list[1] as! Bool
    let fillColor = pigeonVar_list[2] as! Int64
    let center = pigeonVar_list[3] as! PlatformLatLng
    let radius = pigeonVar_list[4] as! Double
    let strokeColor = pigeonVar_list[5] as! Int64
    let strokeWidth = pigeonVar_list[6] as! Int64
    let visible = pigeonVar_list[7] as! Bool
    let zIndex: Int64? = nilOrValue(pigeonVar_list[8])

    return PlatformCircle(
      circleId: circleId,
      consumeTapEvents: consumeTapEvents,
      fillColor: fillColor,
      center: center,
      radius: radius,
      strokeColor: strokeColor,
      strokeWidth: strokeWidth,
      visible: visible,
      zIndex: zIndex
    )
  }
  func toList() -> [Any?] {
    return [
      circleId,
      consumeTapEvents,
      fillColor,
      center,
      radius,
      strokeColor,
      strokeWidth,
      visible,
      zIndex,
    ]
  }
  static func == (lhs: PlatformCircle, rhs: PlatformCircle) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformCircleUpdates: Hashable {
  var circlesToAdd: [PlatformCircle]? = nil
  var circlesToChange: [PlatformCircle]? = nil
  var circleIdsToRemove: [String]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformCircleUpdates? {
    let circlesToAdd: [PlatformCircle]? = nilOrValue(pigeonVar_list[0])
    let circlesToChange: [PlatformCircle]? = nilOrValue(pigeonVar_list[1])
    let circleIdsToRemove: [String]? = nilOrValue(pigeonVar_list[2])

    return PlatformCircleUpdates(
      circlesToAdd: circlesToAdd,
      circlesToChange: circlesToChange,
      circleIdsToRemove: circleIdsToRemove
    )
  }
  func toList() -> [Any?] {
    return [
      circlesToAdd,
      circlesToChange,
      circleIdsToRemove,
    ]
  }
  static func == (lhs: PlatformCircleUpdates, rhs: PlatformCircleUpdates) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformSnapshotOptions: Hashable {
  var showBuildings: Bool
  var showPointsOfInterest: Bool
  var showAnnotations: Bool
  var showOverlays: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformSnapshotOptions? {
    let showBuildings = pigeonVar_list[0] as! Bool
    let showPointsOfInterest = pigeonVar_list[1] as! Bool
    let showAnnotations = pigeonVar_list[2] as! Bool
    let showOverlays = pigeonVar_list[3] as! Bool

    return PlatformSnapshotOptions(
      showBuildings: showBuildings,
      showPointsOfInterest: showPointsOfInterest,
      showAnnotations: showAnnotations,
      showOverlays: showOverlays
    )
  }
  func toList() -> [Any?] {
    return [
      showBuildings,
      showPointsOfInterest,
      showAnnotations,
      showOverlays,
    ]
  }
  static func == (lhs: PlatformSnapshotOptions, rhs: PlatformSnapshotOptions) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PlatformCameraUpdate: Hashable {
  var type: CameraUpdateType
  var cameraPosition: PlatformCameraPosition? = nil
  var latLng: PlatformLatLng? = nil
  var zoom: Double? = nil
  var bounds: PlatformLatLngBounds? = nil
  var padding: Double? = nil
  var focus: PlatformOffset? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PlatformCameraUpdate? {
    let type = pigeonVar_list[0] as! CameraUpdateType
    let cameraPosition: PlatformCameraPosition? = nilOrValue(pigeonVar_list[1])
    let latLng: PlatformLatLng? = nilOrValue(pigeonVar_list[2])
    let zoom: Double? = nilOrValue(pigeonVar_list[3])
    let bounds: PlatformLatLngBounds? = nilOrValue(pigeonVar_list[4])
    let padding: Double? = nilOrValue(pigeonVar_list[5])
    let focus: PlatformOffset? = nilOrValue(pigeonVar_list[6])

    return PlatformCameraUpdate(
      type: type,
      cameraPosition: cameraPosition,
      latLng: latLng,
      zoom: zoom,
      bounds: bounds,
      padding: padding,
      focus: focus
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      cameraPosition,
      latLng,
      zoom,
      bounds,
      padding,
      focus,
    ]
  }
  static func == (lhs: PlatformCameraUpdate, rhs: PlatformCameraUpdate) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return CameraUpdateType(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return BitmapDescriptorType(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return CapType(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PatternItemType(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformMapEmphasisStyle(rawValue: enumResultAsInt)
      }
      return nil
    case 134:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PlatformMapFeatureType(rawValue: enumResultAsInt)
      }
      return nil
    case 135:
      return PlatformOffset.fromList(self.readValue() as! [Any?])
    case 136:
      return PlatformLatLng.fromList(self.readValue() as! [Any?])
    case 137:
      return PlatformLatLngBounds.fromList(self.readValue() as! [Any?])
    case 138:
      return PlatformScreenCoordinate.fromList(self.readValue() as! [Any?])
    case 139:
      return PlatformCameraPosition.fromList(self.readValue() as! [Any?])
    case 140:
      return PlatformMinMaxZoomPreference.fromList(self.readValue() as! [Any?])
    case 141:
      return PlatformPadding.fromList(self.readValue() as! [Any?])
    case 142:
      return PlatformCameraTargetBounds.fromList(self.readValue() as! [Any?])
    case 143:
      return PlatformMapFeature.fromList(self.readValue() as! [Any?])
    case 144:
      return PlatformMapOptions.fromList(self.readValue() as! [Any?])
    case 145:
      return PlatformInfoWindow.fromList(self.readValue() as! [Any?])
    case 146:
      return PlatformBitmapDescriptor.fromList(self.readValue() as! [Any?])
    case 147:
      return PlatformAnnotation.fromList(self.readValue() as! [Any?])
    case 148:
      return PlatformAnnotationUpdates.fromList(self.readValue() as! [Any?])
    case 149:
      return PlatformPatternItem.fromList(self.readValue() as! [Any?])
    case 150:
      return PlatformPolyline.fromList(self.readValue() as! [Any?])
    case 151:
      return PlatformPolylineUpdates.fromList(self.readValue() as! [Any?])
    case 152:
      return PlatformPolygon.fromList(self.readValue() as! [Any?])
    case 153:
      return PlatformPolygonUpdates.fromList(self.readValue() as! [Any?])
    case 154:
      return PlatformCircle.fromList(self.readValue() as! [Any?])
    case 155:
      return PlatformCircleUpdates.fromList(self.readValue() as! [Any?])
    case 156:
      return PlatformSnapshotOptions.fromList(self.readValue() as! [Any?])
    case 157:
      return PlatformCameraUpdate.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? CameraUpdateType {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? BitmapDescriptorType {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? CapType {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? PatternItemType {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformMapEmphasisStyle {
      super.writeByte(133)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformMapFeatureType {
      super.writeByte(134)
      super.writeValue(value.rawValue)
    } else if let value = value as? PlatformOffset {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformLatLng {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformLatLngBounds {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformScreenCoordinate {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformCameraPosition {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformMinMaxZoomPreference {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformPadding {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformCameraTargetBounds {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformMapFeature {
      super.writeByte(143)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformMapOptions {
      super.writeByte(144)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformInfoWindow {
      super.writeByte(145)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformBitmapDescriptor {
      super.writeByte(146)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformAnnotation {
      super.writeByte(147)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformAnnotationUpdates {
      super.writeByte(148)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformPatternItem {
      super.writeByte(149)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformPolyline {
      super.writeByte(150)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformPolylineUpdates {
      super.writeByte(151)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformPolygon {
      super.writeByte(152)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformPolygonUpdates {
      super.writeByte(153)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformCircle {
      super.writeByte(154)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformCircleUpdates {
      super.writeByte(155)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformSnapshotOptions {
      super.writeByte(156)
      super.writeValue(value.toList())
    } else if let value = value as? PlatformCameraUpdate {
      super.writeByte(157)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AppleMapHostApi {
  func updateMapOptions(options: PlatformMapOptions) throws
  func updateAnnotations(updates: PlatformAnnotationUpdates) throws
  func updatePolylines(updates: PlatformPolylineUpdates) throws
  func updatePolygons(updates: PlatformPolygonUpdates) throws
  func updateCircles(updates: PlatformCircleUpdates) throws
  func animateCamera(cameraUpdate: PlatformCameraUpdate) throws
  func moveCamera(cameraUpdate: PlatformCameraUpdate) throws
  func showMarkerInfoWindow(annotationId: String) throws
  func hideMarkerInfoWindow(annotationId: String) throws
  func isMarkerInfoWindowShown(annotationId: String) throws -> Bool?
  func getZoomLevel() throws -> Double?
  func getVisibleRegion() throws -> PlatformLatLngBounds
  func getScreenCoordinate(latLng: PlatformLatLng) throws -> PlatformScreenCoordinate?
  func getLatLng(screenCoordinate: PlatformScreenCoordinate) throws -> PlatformLatLng?
  func takeSnapshot(options: PlatformSnapshotOptions, completion: @escaping (Result<FlutterStandardTypedData?, Error>) -> Void)
  func dispose() throws
  func isCompassEnabled() throws -> Bool
  func getMinMaxZoomLevels() throws -> PlatformMinMaxZoomPreference
  func isZoomGesturesEnabled() throws -> Bool
  func isRotateGesturesEnabled() throws -> Bool
  func isPitchGesturesEnabled() throws -> Bool
  func isScrollGesturesEnabled() throws -> Bool
  func isMyLocationButtonEnabled() throws -> Bool
  func isBuildingsEnabled() throws -> Bool
  func isPointsOfInterestEnabled() throws -> Bool
  func isScaleEnabled() throws -> Bool
  func isTrafficEnabled() throws -> Bool
  func getCameraTargetBounds() throws -> PlatformCameraTargetBounds?
  func deselectSelectedAnnotation() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AppleMapHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `AppleMapHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: AppleMapHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let updateMapOptionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.updateMapOptions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateMapOptionsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let optionsArg = args[0] as! PlatformMapOptions
        do {
          try api.updateMapOptions(options: optionsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateMapOptionsChannel.setMessageHandler(nil)
    }
    let updateAnnotationsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.updateAnnotations\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateAnnotationsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let updatesArg = args[0] as! PlatformAnnotationUpdates
        do {
          try api.updateAnnotations(updates: updatesArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateAnnotationsChannel.setMessageHandler(nil)
    }
    let updatePolylinesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.updatePolylines\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updatePolylinesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let updatesArg = args[0] as! PlatformPolylineUpdates
        do {
          try api.updatePolylines(updates: updatesArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updatePolylinesChannel.setMessageHandler(nil)
    }
    let updatePolygonsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.updatePolygons\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updatePolygonsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let updatesArg = args[0] as! PlatformPolygonUpdates
        do {
          try api.updatePolygons(updates: updatesArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updatePolygonsChannel.setMessageHandler(nil)
    }
    let updateCirclesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.updateCircles\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateCirclesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let updatesArg = args[0] as! PlatformCircleUpdates
        do {
          try api.updateCircles(updates: updatesArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateCirclesChannel.setMessageHandler(nil)
    }
    let animateCameraChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.animateCamera\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      animateCameraChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let cameraUpdateArg = args[0] as! PlatformCameraUpdate
        do {
          try api.animateCamera(cameraUpdate: cameraUpdateArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      animateCameraChannel.setMessageHandler(nil)
    }
    let moveCameraChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.moveCamera\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      moveCameraChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let cameraUpdateArg = args[0] as! PlatformCameraUpdate
        do {
          try api.moveCamera(cameraUpdate: cameraUpdateArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      moveCameraChannel.setMessageHandler(nil)
    }
    let showMarkerInfoWindowChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.showMarkerInfoWindow\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      showMarkerInfoWindowChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let annotationIdArg = args[0] as! String
        do {
          try api.showMarkerInfoWindow(annotationId: annotationIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      showMarkerInfoWindowChannel.setMessageHandler(nil)
    }
    let hideMarkerInfoWindowChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.hideMarkerInfoWindow\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      hideMarkerInfoWindowChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let annotationIdArg = args[0] as! String
        do {
          try api.hideMarkerInfoWindow(annotationId: annotationIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      hideMarkerInfoWindowChannel.setMessageHandler(nil)
    }
    let isMarkerInfoWindowShownChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.isMarkerInfoWindowShown\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isMarkerInfoWindowShownChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let annotationIdArg = args[0] as! String
        do {
          let result = try api.isMarkerInfoWindowShown(annotationId: annotationIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isMarkerInfoWindowShownChannel.setMessageHandler(nil)
    }
    let getZoomLevelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.getZoomLevel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getZoomLevelChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getZoomLevel()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getZoomLevelChannel.setMessageHandler(nil)
    }
    let getVisibleRegionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.getVisibleRegion\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getVisibleRegionChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getVisibleRegion()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getVisibleRegionChannel.setMessageHandler(nil)
    }
    let getScreenCoordinateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.getScreenCoordinate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getScreenCoordinateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let latLngArg = args[0] as! PlatformLatLng
        do {
          let result = try api.getScreenCoordinate(latLng: latLngArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getScreenCoordinateChannel.setMessageHandler(nil)
    }
    let getLatLngChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.getLatLng\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getLatLngChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let screenCoordinateArg = args[0] as! PlatformScreenCoordinate
        do {
          let result = try api.getLatLng(screenCoordinate: screenCoordinateArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getLatLngChannel.setMessageHandler(nil)
    }
    let takeSnapshotChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.takeSnapshot\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      takeSnapshotChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let optionsArg = args[0] as! PlatformSnapshotOptions
        api.takeSnapshot(options: optionsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      takeSnapshotChannel.setMessageHandler(nil)
    }
    let disposeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.dispose\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeChannel.setMessageHandler { _, reply in
        do {
          try api.dispose()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disposeChannel.setMessageHandler(nil)
    }
    let isCompassEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.isCompassEnabled\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isCompassEnabledChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isCompassEnabled()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isCompassEnabledChannel.setMessageHandler(nil)
    }
    let getMinMaxZoomLevelsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.getMinMaxZoomLevels\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getMinMaxZoomLevelsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getMinMaxZoomLevels()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getMinMaxZoomLevelsChannel.setMessageHandler(nil)
    }
    let isZoomGesturesEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.isZoomGesturesEnabled\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isZoomGesturesEnabledChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isZoomGesturesEnabled()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isZoomGesturesEnabledChannel.setMessageHandler(nil)
    }
    let isRotateGesturesEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.isRotateGesturesEnabled\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isRotateGesturesEnabledChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isRotateGesturesEnabled()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isRotateGesturesEnabledChannel.setMessageHandler(nil)
    }
    let isPitchGesturesEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.isPitchGesturesEnabled\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isPitchGesturesEnabledChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isPitchGesturesEnabled()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isPitchGesturesEnabledChannel.setMessageHandler(nil)
    }
    let isScrollGesturesEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.isScrollGesturesEnabled\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isScrollGesturesEnabledChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isScrollGesturesEnabled()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isScrollGesturesEnabledChannel.setMessageHandler(nil)
    }
    let isMyLocationButtonEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.isMyLocationButtonEnabled\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isMyLocationButtonEnabledChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isMyLocationButtonEnabled()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isMyLocationButtonEnabledChannel.setMessageHandler(nil)
    }
    let isBuildingsEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.isBuildingsEnabled\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isBuildingsEnabledChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isBuildingsEnabled()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isBuildingsEnabledChannel.setMessageHandler(nil)
    }
    let isPointsOfInterestEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.isPointsOfInterestEnabled\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isPointsOfInterestEnabledChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isPointsOfInterestEnabled()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isPointsOfInterestEnabledChannel.setMessageHandler(nil)
    }
    let isScaleEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.isScaleEnabled\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isScaleEnabledChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isScaleEnabled()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isScaleEnabledChannel.setMessageHandler(nil)
    }
    let isTrafficEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.isTrafficEnabled\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isTrafficEnabledChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isTrafficEnabled()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isTrafficEnabledChannel.setMessageHandler(nil)
    }
    let getCameraTargetBoundsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.getCameraTargetBounds\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCameraTargetBoundsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getCameraTargetBounds()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getCameraTargetBoundsChannel.setMessageHandler(nil)
    }
    let deselectSelectedAnnotationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.deselectSelectedAnnotation\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      deselectSelectedAnnotationChannel.setMessageHandler { _, reply in
        do {
          try api.deselectSelectedAnnotation()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      deselectSelectedAnnotationChannel.setMessageHandler(nil)
    }
  }
}
/// Callbacks from the native map to Flutter.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol AppleMapFlutterApiProtocol {
  func onCameraMoveStarted(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onCameraMove(position positionArg: PlatformCameraPosition, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onCameraIdle(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onMapTap(position positionArg: PlatformLatLng, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onMapLongPress(position positionArg: PlatformLatLng, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onAnnotationTap(annotationId annotationIdArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onAnnotationDragEnd(annotationId annotationIdArg: String, position positionArg: PlatformLatLng, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onAnnotationZIndexChanged(annotationId annotationIdArg: String, zIndex zIndexArg: Double, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onInfoWindowTap(annotationId annotationIdArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onPolylineTap(polylineId polylineIdArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onPolygonTap(polygonId polygonIdArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onCircleTap(circleId circleIdArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onPermissionDenied(completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Called when the user taps a built-in map feature such as a POI or
  /// landmark. Only fires on iOS 16+; ignored on earlier OS versions.
  func onMapFeatureTapped(feature featureArg: PlatformMapFeature, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class AppleMapFlutterApi: AppleMapFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  func onCameraMoveStarted(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onCameraMoveStarted\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onCameraMove(position positionArg: PlatformCameraPosition, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onCameraMove\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([positionArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onCameraIdle(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onCameraIdle\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onMapTap(position positionArg: PlatformLatLng, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onMapTap\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([positionArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onMapLongPress(position positionArg: PlatformLatLng, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onMapLongPress\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([positionArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onAnnotationTap(annotationId annotationIdArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onAnnotationTap\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([annotationIdArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onAnnotationDragEnd(annotationId annotationIdArg: String, position positionArg: PlatformLatLng, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onAnnotationDragEnd\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([annotationIdArg, positionArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onAnnotationZIndexChanged(annotationId annotationIdArg: String, zIndex zIndexArg: Double, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onAnnotationZIndexChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([annotationIdArg, zIndexArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onInfoWindowTap(annotationId annotationIdArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onInfoWindowTap\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([annotationIdArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onPolylineTap(polylineId polylineIdArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onPolylineTap\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([polylineIdArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onPolygonTap(polygonId polygonIdArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onPolygonTap\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([polygonIdArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onCircleTap(circleId circleIdArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onCircleTap\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([circleIdArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onPermissionDenied(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onPermissionDenied\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  /// Called when the user taps a built-in map feature such as a POI or
  /// landmark. Only fires on iOS 16+; ignored on earlier OS versions.
  func onMapFeatureTapped(feature featureArg: PlatformMapFeature, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onMapFeatureTapped\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([featureArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
