// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({
  Object? result,
  PlatformException? error,
  bool empty = false,
}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    return a.length == b.length &&
        a.entries.every(
          (MapEntry<Object?, Object?> entry) =>
              (b as Map<Object?, Object?>).containsKey(entry.key) &&
              _deepEquals(entry.value, b[entry.key]),
        );
  }
  return a == b;
}

enum CameraUpdateType {
  newCameraPosition,
  newLatLng,
  newLatLngZoom,
  newLatLngBounds,
  zoomBy,
  zoomTo,
  zoomIn,
  zoomOut,
}

enum BitmapDescriptorType {
  defaultAnnotation,
  markerAnnotation,
  fromAssetImage,
  fromBytes,
}

enum CapType { buttCap, roundCap, squareCap }

enum PatternItemType { dot, dash, gap }

/// Emphasis style for the standard map configuration (iOS 16+).
enum PlatformMapEmphasisStyle {
  /// The default map appearance.
  defaultStyle,

  /// A muted appearance that de-emphasises labels and icons.
  muted,
}

/// The type of a built-in map feature tapped by the user (iOS 16+).
enum PlatformMapFeatureType { pointOfInterest, territory, physicalFeature }

class PlatformOffset {
  PlatformOffset({required this.x, required this.y});

  double x;

  double y;

  List<Object?> _toList() {
    return <Object?>[x, y];
  }

  Object encode() {
    return _toList();
  }

  static PlatformOffset decode(Object result) {
    result as List<Object?>;
    return PlatformOffset(x: result[0]! as double, y: result[1]! as double);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformOffset || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class PlatformLatLng {
  PlatformLatLng({required this.latitude, required this.longitude});

  double latitude;

  double longitude;

  List<Object?> _toList() {
    return <Object?>[latitude, longitude];
  }

  Object encode() {
    return _toList();
  }

  static PlatformLatLng decode(Object result) {
    result as List<Object?>;
    return PlatformLatLng(
      latitude: result[0]! as double,
      longitude: result[1]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformLatLng || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class PlatformLatLngBounds {
  PlatformLatLngBounds({required this.southwest, required this.northeast});

  PlatformLatLng southwest;

  PlatformLatLng northeast;

  List<Object?> _toList() {
    return <Object?>[southwest, northeast];
  }

  Object encode() {
    return _toList();
  }

  static PlatformLatLngBounds decode(Object result) {
    result as List<Object?>;
    return PlatformLatLngBounds(
      southwest: result[0]! as PlatformLatLng,
      northeast: result[1]! as PlatformLatLng,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformLatLngBounds || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class PlatformScreenCoordinate {
  PlatformScreenCoordinate({required this.x, required this.y});

  double x;

  double y;

  List<Object?> _toList() {
    return <Object?>[x, y];
  }

  Object encode() {
    return _toList();
  }

  static PlatformScreenCoordinate decode(Object result) {
    result as List<Object?>;
    return PlatformScreenCoordinate(
      x: result[0]! as double,
      y: result[1]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformScreenCoordinate ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class PlatformCameraPosition {
  PlatformCameraPosition({
    required this.target,
    required this.heading,
    required this.pitch,
    required this.zoom,
  });

  PlatformLatLng target;

  double heading;

  double pitch;

  double zoom;

  List<Object?> _toList() {
    return <Object?>[target, heading, pitch, zoom];
  }

  Object encode() {
    return _toList();
  }

  static PlatformCameraPosition decode(Object result) {
    result as List<Object?>;
    return PlatformCameraPosition(
      target: result[0]! as PlatformLatLng,
      heading: result[1]! as double,
      pitch: result[2]! as double,
      zoom: result[3]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformCameraPosition || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class PlatformMinMaxZoomPreference {
  PlatformMinMaxZoomPreference({this.minZoom, this.maxZoom});

  double? minZoom;

  double? maxZoom;

  List<Object?> _toList() {
    return <Object?>[minZoom, maxZoom];
  }

  Object encode() {
    return _toList();
  }

  static PlatformMinMaxZoomPreference decode(Object result) {
    result as List<Object?>;
    return PlatformMinMaxZoomPreference(
      minZoom: result[0] as double?,
      maxZoom: result[1] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformMinMaxZoomPreference ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class PlatformPadding {
  PlatformPadding({
    required this.top,
    required this.left,
    required this.bottom,
    required this.right,
  });

  double top;

  double left;

  double bottom;

  double right;

  List<Object?> _toList() {
    return <Object?>[top, left, bottom, right];
  }

  Object encode() {
    return _toList();
  }

  static PlatformPadding decode(Object result) {
    result as List<Object?>;
    return PlatformPadding(
      top: result[0]! as double,
      left: result[1]! as double,
      bottom: result[2]! as double,
      right: result[3]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformPadding || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class PlatformCameraTargetBounds {
  PlatformCameraTargetBounds({this.bounds});

  PlatformLatLngBounds? bounds;

  List<Object?> _toList() {
    return <Object?>[bounds];
  }

  Object encode() {
    return _toList();
  }

  static PlatformCameraTargetBounds decode(Object result) {
    result as List<Object?>;
    return PlatformCameraTargetBounds(
      bounds: result[0] as PlatformLatLngBounds?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformCameraTargetBounds ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

/// A built-in map feature (e.g. POI, landmark) selected by the user (iOS 16+).
class PlatformMapFeature {
  PlatformMapFeature({
    required this.coordinate,
    required this.featureType,
    this.title,
    this.pointOfInterestCategory,
  });

  PlatformLatLng coordinate;

  PlatformMapFeatureType featureType;

  /// The display title of the feature, if available.
  String? title;

  /// The raw `MKPointOfInterestCategory` string value for `.pointOfInterest`
  /// features, e.g. `"MKPOICategoryRestaurant"`. Null for other feature types.
  String? pointOfInterestCategory;

  List<Object?> _toList() {
    return <Object?>[coordinate, featureType, title, pointOfInterestCategory];
  }

  Object encode() {
    return _toList();
  }

  static PlatformMapFeature decode(Object result) {
    result as List<Object?>;
    return PlatformMapFeature(
      coordinate: result[0]! as PlatformLatLng,
      featureType: result[1]! as PlatformMapFeatureType,
      title: result[2] as String?,
      pointOfInterestCategory: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformMapFeature || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class PlatformMapOptions {
  PlatformMapOptions({
    this.compassEnabled,
    this.trafficEnabled,
    this.mapType,
    this.minMaxZoomPreference,
    this.rotateGesturesEnabled,
    this.scrollGesturesEnabled,
    this.pitchGesturesEnabled,
    this.trackingMode,
    this.zoomGesturesEnabled,
    this.myLocationEnabled,
    this.myLocationButtonEnabled,
    this.padding,
    this.insetsLayoutMarginsFromSafeArea,
    this.cameraTargetBounds,
    this.buildingsEnabled,
    this.pointsOfInterestEnabled,
    this.scaleEnabled,
    this.emphasisStyle,
    this.selectableFeatures,
  });

  bool? compassEnabled;

  bool? trafficEnabled;

  int? mapType;

  PlatformMinMaxZoomPreference? minMaxZoomPreference;

  bool? rotateGesturesEnabled;

  bool? scrollGesturesEnabled;

  bool? pitchGesturesEnabled;

  int? trackingMode;

  bool? zoomGesturesEnabled;

  bool? myLocationEnabled;

  bool? myLocationButtonEnabled;

  PlatformPadding? padding;

  bool? insetsLayoutMarginsFromSafeArea;

  PlatformCameraTargetBounds? cameraTargetBounds;

  bool? buildingsEnabled;

  bool? pointsOfInterestEnabled;

  bool? scaleEnabled;

  /// Emphasis style for the standard map (iOS 16+, no-op on other map types).
  PlatformMapEmphasisStyle? emphasisStyle;

  /// Bitmask of selectable built-in map features (iOS 16+).
  /// Bit 0 = pointsOfInterest, bit 1 = territories, bit 2 = physicalFeatures.
  int? selectableFeatures;

  List<Object?> _toList() {
    return <Object?>[
      compassEnabled,
      trafficEnabled,
      mapType,
      minMaxZoomPreference,
      rotateGesturesEnabled,
      scrollGesturesEnabled,
      pitchGesturesEnabled,
      trackingMode,
      zoomGesturesEnabled,
      myLocationEnabled,
      myLocationButtonEnabled,
      padding,
      insetsLayoutMarginsFromSafeArea,
      cameraTargetBounds,
      buildingsEnabled,
      pointsOfInterestEnabled,
      scaleEnabled,
      emphasisStyle,
      selectableFeatures,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PlatformMapOptions decode(Object result) {
    result as List<Object?>;
    return PlatformMapOptions(
      compassEnabled: result[0] as bool?,
      trafficEnabled: result[1] as bool?,
      mapType: result[2] as int?,
      minMaxZoomPreference: result[3] as PlatformMinMaxZoomPreference?,
      rotateGesturesEnabled: result[4] as bool?,
      scrollGesturesEnabled: result[5] as bool?,
      pitchGesturesEnabled: result[6] as bool?,
      trackingMode: result[7] as int?,
      zoomGesturesEnabled: result[8] as bool?,
      myLocationEnabled: result[9] as bool?,
      myLocationButtonEnabled: result[10] as bool?,
      padding: result[11] as PlatformPadding?,
      insetsLayoutMarginsFromSafeArea: result[12] as bool?,
      cameraTargetBounds: result[13] as PlatformCameraTargetBounds?,
      buildingsEnabled: result[14] as bool?,
      pointsOfInterestEnabled: result[15] as bool?,
      scaleEnabled: result[16] as bool?,
      emphasisStyle: result[17] as PlatformMapEmphasisStyle?,
      selectableFeatures: result[18] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformMapOptions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class PlatformInfoWindow {
  PlatformInfoWindow({
    this.title,
    this.snippet,
    this.anchor,
    required this.consumesTapEvents,
  });

  String? title;

  String? snippet;

  PlatformOffset? anchor;

  bool consumesTapEvents;

  List<Object?> _toList() {
    return <Object?>[title, snippet, anchor, consumesTapEvents];
  }

  Object encode() {
    return _toList();
  }

  static PlatformInfoWindow decode(Object result) {
    result as List<Object?>;
    return PlatformInfoWindow(
      title: result[0] as String?,
      snippet: result[1] as String?,
      anchor: result[2] as PlatformOffset?,
      consumesTapEvents: result[3]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformInfoWindow || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class PlatformBitmapDescriptor {
  PlatformBitmapDescriptor({
    required this.type,
    this.hue,
    this.assetName,
    this.assetScale,
    this.bytes,
  });

  BitmapDescriptorType type;

  double? hue;

  String? assetName;

  double? assetScale;

  Uint8List? bytes;

  List<Object?> _toList() {
    return <Object?>[type, hue, assetName, assetScale, bytes];
  }

  Object encode() {
    return _toList();
  }

  static PlatformBitmapDescriptor decode(Object result) {
    result as List<Object?>;
    return PlatformBitmapDescriptor(
      type: result[0]! as BitmapDescriptorType,
      hue: result[1] as double?,
      assetName: result[2] as String?,
      assetScale: result[3] as double?,
      bytes: result[4] as Uint8List?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformBitmapDescriptor ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class PlatformAnnotation {
  PlatformAnnotation({
    required this.annotationId,
    required this.alpha,
    required this.anchor,
    required this.draggable,
    required this.icon,
    required this.infoWindow,
    required this.visible,
    required this.position,
    required this.zIndex,
    this.clusteringIdentifier,
  });

  String annotationId;

  double alpha;

  PlatformOffset anchor;

  bool draggable;

  PlatformBitmapDescriptor icon;

  PlatformInfoWindow infoWindow;

  bool visible;

  PlatformLatLng position;

  double zIndex;

  /// When set, annotations with the same identifier are eligible for clustering.
  /// Maps to MKAnnotationView.clusteringIdentifier on iOS 11+.
  String? clusteringIdentifier;

  List<Object?> _toList() {
    return <Object?>[
      annotationId,
      alpha,
      anchor,
      draggable,
      icon,
      infoWindow,
      visible,
      position,
      zIndex,
      clusteringIdentifier,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PlatformAnnotation decode(Object result) {
    result as List<Object?>;
    return PlatformAnnotation(
      annotationId: result[0]! as String,
      alpha: result[1]! as double,
      anchor: result[2]! as PlatformOffset,
      draggable: result[3]! as bool,
      icon: result[4]! as PlatformBitmapDescriptor,
      infoWindow: result[5]! as PlatformInfoWindow,
      visible: result[6]! as bool,
      position: result[7]! as PlatformLatLng,
      zIndex: result[8]! as double,
      clusteringIdentifier: result[9] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformAnnotation || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class PlatformAnnotationUpdates {
  PlatformAnnotationUpdates({
    this.annotationsToAdd,
    this.annotationsToChange,
    this.annotationIdsToRemove,
  });

  List<PlatformAnnotation>? annotationsToAdd;

  List<PlatformAnnotation>? annotationsToChange;

  List<String>? annotationIdsToRemove;

  List<Object?> _toList() {
    return <Object?>[
      annotationsToAdd,
      annotationsToChange,
      annotationIdsToRemove,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PlatformAnnotationUpdates decode(Object result) {
    result as List<Object?>;
    return PlatformAnnotationUpdates(
      annotationsToAdd: (result[0] as List<Object?>?)
          ?.cast<PlatformAnnotation>(),
      annotationsToChange: (result[1] as List<Object?>?)
          ?.cast<PlatformAnnotation>(),
      annotationIdsToRemove: (result[2] as List<Object?>?)?.cast<String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformAnnotationUpdates ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class PlatformPatternItem {
  PlatformPatternItem({required this.type, this.length});

  PatternItemType type;

  double? length;

  List<Object?> _toList() {
    return <Object?>[type, length];
  }

  Object encode() {
    return _toList();
  }

  static PlatformPatternItem decode(Object result) {
    result as List<Object?>;
    return PlatformPatternItem(
      type: result[0]! as PatternItemType,
      length: result[1] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformPatternItem || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class PlatformPolyline {
  PlatformPolyline({
    required this.polylineId,
    required this.consumeTapEvents,
    required this.color,
    required this.polylineCap,
    required this.jointType,
    required this.visible,
    required this.width,
    this.zIndex,
    required this.points,
    required this.patterns,
  });

  String polylineId;

  bool consumeTapEvents;

  int color;

  CapType polylineCap;

  int jointType;

  bool visible;

  int width;

  int? zIndex;

  List<PlatformLatLng> points;

  List<PlatformPatternItem> patterns;

  List<Object?> _toList() {
    return <Object?>[
      polylineId,
      consumeTapEvents,
      color,
      polylineCap,
      jointType,
      visible,
      width,
      zIndex,
      points,
      patterns,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PlatformPolyline decode(Object result) {
    result as List<Object?>;
    return PlatformPolyline(
      polylineId: result[0]! as String,
      consumeTapEvents: result[1]! as bool,
      color: result[2]! as int,
      polylineCap: result[3]! as CapType,
      jointType: result[4]! as int,
      visible: result[5]! as bool,
      width: result[6]! as int,
      zIndex: result[7] as int?,
      points: (result[8] as List<Object?>?)!.cast<PlatformLatLng>(),
      patterns: (result[9] as List<Object?>?)!.cast<PlatformPatternItem>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformPolyline || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class PlatformPolylineUpdates {
  PlatformPolylineUpdates({
    this.polylinesToAdd,
    this.polylinesToChange,
    this.polylineIdsToRemove,
  });

  List<PlatformPolyline>? polylinesToAdd;

  List<PlatformPolyline>? polylinesToChange;

  List<String>? polylineIdsToRemove;

  List<Object?> _toList() {
    return <Object?>[polylinesToAdd, polylinesToChange, polylineIdsToRemove];
  }

  Object encode() {
    return _toList();
  }

  static PlatformPolylineUpdates decode(Object result) {
    result as List<Object?>;
    return PlatformPolylineUpdates(
      polylinesToAdd: (result[0] as List<Object?>?)?.cast<PlatformPolyline>(),
      polylinesToChange: (result[1] as List<Object?>?)
          ?.cast<PlatformPolyline>(),
      polylineIdsToRemove: (result[2] as List<Object?>?)?.cast<String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformPolylineUpdates || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class PlatformPolygon {
  PlatformPolygon({
    required this.polygonId,
    required this.consumeTapEvents,
    required this.fillColor,
    required this.points,
    required this.strokeColor,
    required this.strokeWidth,
    required this.visible,
    this.zIndex,
  });

  String polygonId;

  bool consumeTapEvents;

  int fillColor;

  List<PlatformLatLng> points;

  int strokeColor;

  int strokeWidth;

  bool visible;

  int? zIndex;

  List<Object?> _toList() {
    return <Object?>[
      polygonId,
      consumeTapEvents,
      fillColor,
      points,
      strokeColor,
      strokeWidth,
      visible,
      zIndex,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PlatformPolygon decode(Object result) {
    result as List<Object?>;
    return PlatformPolygon(
      polygonId: result[0]! as String,
      consumeTapEvents: result[1]! as bool,
      fillColor: result[2]! as int,
      points: (result[3] as List<Object?>?)!.cast<PlatformLatLng>(),
      strokeColor: result[4]! as int,
      strokeWidth: result[5]! as int,
      visible: result[6]! as bool,
      zIndex: result[7] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformPolygon || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class PlatformPolygonUpdates {
  PlatformPolygonUpdates({
    this.polygonsToAdd,
    this.polygonsToChange,
    this.polygonIdsToRemove,
  });

  List<PlatformPolygon>? polygonsToAdd;

  List<PlatformPolygon>? polygonsToChange;

  List<String>? polygonIdsToRemove;

  List<Object?> _toList() {
    return <Object?>[polygonsToAdd, polygonsToChange, polygonIdsToRemove];
  }

  Object encode() {
    return _toList();
  }

  static PlatformPolygonUpdates decode(Object result) {
    result as List<Object?>;
    return PlatformPolygonUpdates(
      polygonsToAdd: (result[0] as List<Object?>?)?.cast<PlatformPolygon>(),
      polygonsToChange: (result[1] as List<Object?>?)?.cast<PlatformPolygon>(),
      polygonIdsToRemove: (result[2] as List<Object?>?)?.cast<String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformPolygonUpdates || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class PlatformCircle {
  PlatformCircle({
    required this.circleId,
    required this.consumeTapEvents,
    required this.fillColor,
    required this.center,
    required this.radius,
    required this.strokeColor,
    required this.strokeWidth,
    required this.visible,
    this.zIndex,
  });

  String circleId;

  bool consumeTapEvents;

  int fillColor;

  PlatformLatLng center;

  double radius;

  int strokeColor;

  int strokeWidth;

  bool visible;

  int? zIndex;

  List<Object?> _toList() {
    return <Object?>[
      circleId,
      consumeTapEvents,
      fillColor,
      center,
      radius,
      strokeColor,
      strokeWidth,
      visible,
      zIndex,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PlatformCircle decode(Object result) {
    result as List<Object?>;
    return PlatformCircle(
      circleId: result[0]! as String,
      consumeTapEvents: result[1]! as bool,
      fillColor: result[2]! as int,
      center: result[3]! as PlatformLatLng,
      radius: result[4]! as double,
      strokeColor: result[5]! as int,
      strokeWidth: result[6]! as int,
      visible: result[7]! as bool,
      zIndex: result[8] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformCircle || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class PlatformCircleUpdates {
  PlatformCircleUpdates({
    this.circlesToAdd,
    this.circlesToChange,
    this.circleIdsToRemove,
  });

  List<PlatformCircle>? circlesToAdd;

  List<PlatformCircle>? circlesToChange;

  List<String>? circleIdsToRemove;

  List<Object?> _toList() {
    return <Object?>[circlesToAdd, circlesToChange, circleIdsToRemove];
  }

  Object encode() {
    return _toList();
  }

  static PlatformCircleUpdates decode(Object result) {
    result as List<Object?>;
    return PlatformCircleUpdates(
      circlesToAdd: (result[0] as List<Object?>?)?.cast<PlatformCircle>(),
      circlesToChange: (result[1] as List<Object?>?)?.cast<PlatformCircle>(),
      circleIdsToRemove: (result[2] as List<Object?>?)?.cast<String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformCircleUpdates || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class PlatformSnapshotOptions {
  PlatformSnapshotOptions({
    required this.showBuildings,
    required this.showPointsOfInterest,
    required this.showAnnotations,
    required this.showOverlays,
  });

  bool showBuildings;

  bool showPointsOfInterest;

  bool showAnnotations;

  bool showOverlays;

  List<Object?> _toList() {
    return <Object?>[
      showBuildings,
      showPointsOfInterest,
      showAnnotations,
      showOverlays,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PlatformSnapshotOptions decode(Object result) {
    result as List<Object?>;
    return PlatformSnapshotOptions(
      showBuildings: result[0]! as bool,
      showPointsOfInterest: result[1]! as bool,
      showAnnotations: result[2]! as bool,
      showOverlays: result[3]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformSnapshotOptions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class PlatformCameraUpdate {
  PlatformCameraUpdate({
    required this.type,
    this.cameraPosition,
    this.latLng,
    this.zoom,
    this.bounds,
    this.padding,
    this.focus,
  });

  CameraUpdateType type;

  PlatformCameraPosition? cameraPosition;

  PlatformLatLng? latLng;

  double? zoom;

  PlatformLatLngBounds? bounds;

  double? padding;

  PlatformOffset? focus;

  List<Object?> _toList() {
    return <Object?>[
      type,
      cameraPosition,
      latLng,
      zoom,
      bounds,
      padding,
      focus,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PlatformCameraUpdate decode(Object result) {
    result as List<Object?>;
    return PlatformCameraUpdate(
      type: result[0]! as CameraUpdateType,
      cameraPosition: result[1] as PlatformCameraPosition?,
      latLng: result[2] as PlatformLatLng?,
      zoom: result[3] as double?,
      bounds: result[4] as PlatformLatLngBounds?,
      padding: result[5] as double?,
      focus: result[6] as PlatformOffset?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformCameraUpdate || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is CameraUpdateType) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is BitmapDescriptorType) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is CapType) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is PatternItemType) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    } else if (value is PlatformMapEmphasisStyle) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    } else if (value is PlatformMapFeatureType) {
      buffer.putUint8(134);
      writeValue(buffer, value.index);
    } else if (value is PlatformOffset) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is PlatformLatLng) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is PlatformLatLngBounds) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else if (value is PlatformScreenCoordinate) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else if (value is PlatformCameraPosition) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else if (value is PlatformMinMaxZoomPreference) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else if (value is PlatformPadding) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    } else if (value is PlatformCameraTargetBounds) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    } else if (value is PlatformMapFeature) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    } else if (value is PlatformMapOptions) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    } else if (value is PlatformInfoWindow) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    } else if (value is PlatformBitmapDescriptor) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    } else if (value is PlatformAnnotation) {
      buffer.putUint8(147);
      writeValue(buffer, value.encode());
    } else if (value is PlatformAnnotationUpdates) {
      buffer.putUint8(148);
      writeValue(buffer, value.encode());
    } else if (value is PlatformPatternItem) {
      buffer.putUint8(149);
      writeValue(buffer, value.encode());
    } else if (value is PlatformPolyline) {
      buffer.putUint8(150);
      writeValue(buffer, value.encode());
    } else if (value is PlatformPolylineUpdates) {
      buffer.putUint8(151);
      writeValue(buffer, value.encode());
    } else if (value is PlatformPolygon) {
      buffer.putUint8(152);
      writeValue(buffer, value.encode());
    } else if (value is PlatformPolygonUpdates) {
      buffer.putUint8(153);
      writeValue(buffer, value.encode());
    } else if (value is PlatformCircle) {
      buffer.putUint8(154);
      writeValue(buffer, value.encode());
    } else if (value is PlatformCircleUpdates) {
      buffer.putUint8(155);
      writeValue(buffer, value.encode());
    } else if (value is PlatformSnapshotOptions) {
      buffer.putUint8(156);
      writeValue(buffer, value.encode());
    } else if (value is PlatformCameraUpdate) {
      buffer.putUint8(157);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : CameraUpdateType.values[value];
      case 130:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : BitmapDescriptorType.values[value];
      case 131:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : CapType.values[value];
      case 132:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : PatternItemType.values[value];
      case 133:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : PlatformMapEmphasisStyle.values[value];
      case 134:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : PlatformMapFeatureType.values[value];
      case 135:
        return PlatformOffset.decode(readValue(buffer)!);
      case 136:
        return PlatformLatLng.decode(readValue(buffer)!);
      case 137:
        return PlatformLatLngBounds.decode(readValue(buffer)!);
      case 138:
        return PlatformScreenCoordinate.decode(readValue(buffer)!);
      case 139:
        return PlatformCameraPosition.decode(readValue(buffer)!);
      case 140:
        return PlatformMinMaxZoomPreference.decode(readValue(buffer)!);
      case 141:
        return PlatformPadding.decode(readValue(buffer)!);
      case 142:
        return PlatformCameraTargetBounds.decode(readValue(buffer)!);
      case 143:
        return PlatformMapFeature.decode(readValue(buffer)!);
      case 144:
        return PlatformMapOptions.decode(readValue(buffer)!);
      case 145:
        return PlatformInfoWindow.decode(readValue(buffer)!);
      case 146:
        return PlatformBitmapDescriptor.decode(readValue(buffer)!);
      case 147:
        return PlatformAnnotation.decode(readValue(buffer)!);
      case 148:
        return PlatformAnnotationUpdates.decode(readValue(buffer)!);
      case 149:
        return PlatformPatternItem.decode(readValue(buffer)!);
      case 150:
        return PlatformPolyline.decode(readValue(buffer)!);
      case 151:
        return PlatformPolylineUpdates.decode(readValue(buffer)!);
      case 152:
        return PlatformPolygon.decode(readValue(buffer)!);
      case 153:
        return PlatformPolygonUpdates.decode(readValue(buffer)!);
      case 154:
        return PlatformCircle.decode(readValue(buffer)!);
      case 155:
        return PlatformCircleUpdates.decode(readValue(buffer)!);
      case 156:
        return PlatformSnapshotOptions.decode(readValue(buffer)!);
      case 157:
        return PlatformCameraUpdate.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class AppleMapHostApi {
  /// Constructor for [AppleMapHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  AppleMapHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> updateMapOptions(PlatformMapOptions options) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.updateMapOptions$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[options],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> updateAnnotations(PlatformAnnotationUpdates updates) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.updateAnnotations$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[updates],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> updatePolylines(PlatformPolylineUpdates updates) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.updatePolylines$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[updates],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> updatePolygons(PlatformPolygonUpdates updates) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.updatePolygons$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[updates],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> updateCircles(PlatformCircleUpdates updates) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.updateCircles$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[updates],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> animateCamera(PlatformCameraUpdate cameraUpdate) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.animateCamera$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[cameraUpdate],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> moveCamera(PlatformCameraUpdate cameraUpdate) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.moveCamera$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[cameraUpdate],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> showMarkerInfoWindow(String annotationId) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.showMarkerInfoWindow$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[annotationId],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> hideMarkerInfoWindow(String annotationId) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.hideMarkerInfoWindow$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[annotationId],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<bool?> isMarkerInfoWindowShown(String annotationId) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.isMarkerInfoWindowShown$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[annotationId],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as bool?);
    }
  }

  Future<double?> getZoomLevel() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.getZoomLevel$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as double?);
    }
  }

  Future<PlatformLatLngBounds> getVisibleRegion() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.getVisibleRegion$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as PlatformLatLngBounds?)!;
    }
  }

  Future<PlatformScreenCoordinate?> getScreenCoordinate(
    PlatformLatLng latLng,
  ) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.getScreenCoordinate$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[latLng],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as PlatformScreenCoordinate?);
    }
  }

  Future<PlatformLatLng?> getLatLng(
    PlatformScreenCoordinate screenCoordinate,
  ) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.getLatLng$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[screenCoordinate],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as PlatformLatLng?);
    }
  }

  Future<Uint8List?> takeSnapshot(PlatformSnapshotOptions options) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.takeSnapshot$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[options],
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as Uint8List?);
    }
  }

  Future<void> dispose() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.dispose$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<bool> isCompassEnabled() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.isCompassEnabled$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<PlatformMinMaxZoomPreference> getMinMaxZoomLevels() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.getMinMaxZoomLevels$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as PlatformMinMaxZoomPreference?)!;
    }
  }

  Future<bool> isZoomGesturesEnabled() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.isZoomGesturesEnabled$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<bool> isRotateGesturesEnabled() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.isRotateGesturesEnabled$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<bool> isPitchGesturesEnabled() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.isPitchGesturesEnabled$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<bool> isScrollGesturesEnabled() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.isScrollGesturesEnabled$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<bool> isMyLocationButtonEnabled() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.isMyLocationButtonEnabled$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<bool> isBuildingsEnabled() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.isBuildingsEnabled$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<bool> isPointsOfInterestEnabled() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.isPointsOfInterestEnabled$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<bool> isScaleEnabled() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.isScaleEnabled$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<bool> isTrafficEnabled() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.isTrafficEnabled$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  Future<PlatformCameraTargetBounds?> getCameraTargetBounds() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.getCameraTargetBounds$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as PlatformCameraTargetBounds?);
    }
  }

  Future<void> deselectSelectedAnnotation() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.apple_maps_flutter.AppleMapHostApi.deselectSelectedAnnotation$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
          pigeonVar_channelName,
          pigeonChannelCodec,
          binaryMessenger: pigeonVar_binaryMessenger,
        );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}

/// Callbacks from the native map to Flutter.
abstract class AppleMapFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onCameraMoveStarted();

  void onCameraMove(PlatformCameraPosition position);

  void onCameraIdle();

  void onMapTap(PlatformLatLng position);

  void onMapLongPress(PlatformLatLng position);

  void onAnnotationTap(String annotationId);

  void onAnnotationDragEnd(String annotationId, PlatformLatLng position);

  void onAnnotationZIndexChanged(String annotationId, double zIndex);

  void onInfoWindowTap(String annotationId);

  void onPolylineTap(String polylineId);

  void onPolygonTap(String polygonId);

  void onCircleTap(String circleId);

  void onPermissionDenied();

  /// Called when the user taps a built-in map feature such as a POI or
  /// landmark. Only fires on iOS 16+; ignored on earlier OS versions.
  void onMapFeatureTapped(PlatformMapFeature feature);

  static void setUp(
    AppleMapFlutterApi? api, {
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty
        ? '.$messageChannelSuffix'
        : '';
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onCameraMoveStarted$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onCameraMoveStarted();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onCameraMove$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onCameraMove was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final PlatformCameraPosition? arg_position =
              (args[0] as PlatformCameraPosition?);
          assert(
            arg_position != null,
            'Argument for dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onCameraMove was null, expected non-null PlatformCameraPosition.',
          );
          try {
            api.onCameraMove(arg_position!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onCameraIdle$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onCameraIdle();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onMapTap$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onMapTap was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final PlatformLatLng? arg_position = (args[0] as PlatformLatLng?);
          assert(
            arg_position != null,
            'Argument for dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onMapTap was null, expected non-null PlatformLatLng.',
          );
          try {
            api.onMapTap(arg_position!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onMapLongPress$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onMapLongPress was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final PlatformLatLng? arg_position = (args[0] as PlatformLatLng?);
          assert(
            arg_position != null,
            'Argument for dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onMapLongPress was null, expected non-null PlatformLatLng.',
          );
          try {
            api.onMapLongPress(arg_position!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onAnnotationTap$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onAnnotationTap was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_annotationId = (args[0] as String?);
          assert(
            arg_annotationId != null,
            'Argument for dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onAnnotationTap was null, expected non-null String.',
          );
          try {
            api.onAnnotationTap(arg_annotationId!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onAnnotationDragEnd$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onAnnotationDragEnd was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_annotationId = (args[0] as String?);
          assert(
            arg_annotationId != null,
            'Argument for dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onAnnotationDragEnd was null, expected non-null String.',
          );
          final PlatformLatLng? arg_position = (args[1] as PlatformLatLng?);
          assert(
            arg_position != null,
            'Argument for dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onAnnotationDragEnd was null, expected non-null PlatformLatLng.',
          );
          try {
            api.onAnnotationDragEnd(arg_annotationId!, arg_position!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onAnnotationZIndexChanged$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onAnnotationZIndexChanged was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_annotationId = (args[0] as String?);
          assert(
            arg_annotationId != null,
            'Argument for dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onAnnotationZIndexChanged was null, expected non-null String.',
          );
          final double? arg_zIndex = (args[1] as double?);
          assert(
            arg_zIndex != null,
            'Argument for dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onAnnotationZIndexChanged was null, expected non-null double.',
          );
          try {
            api.onAnnotationZIndexChanged(arg_annotationId!, arg_zIndex!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onInfoWindowTap$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onInfoWindowTap was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_annotationId = (args[0] as String?);
          assert(
            arg_annotationId != null,
            'Argument for dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onInfoWindowTap was null, expected non-null String.',
          );
          try {
            api.onInfoWindowTap(arg_annotationId!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onPolylineTap$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onPolylineTap was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_polylineId = (args[0] as String?);
          assert(
            arg_polylineId != null,
            'Argument for dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onPolylineTap was null, expected non-null String.',
          );
          try {
            api.onPolylineTap(arg_polylineId!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onPolygonTap$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onPolygonTap was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_polygonId = (args[0] as String?);
          assert(
            arg_polygonId != null,
            'Argument for dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onPolygonTap was null, expected non-null String.',
          );
          try {
            api.onPolygonTap(arg_polygonId!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onCircleTap$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onCircleTap was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_circleId = (args[0] as String?);
          assert(
            arg_circleId != null,
            'Argument for dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onCircleTap was null, expected non-null String.',
          );
          try {
            api.onCircleTap(arg_circleId!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onPermissionDenied$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onPermissionDenied();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?>
      pigeonVar_channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onMapFeatureTapped$messageChannelSuffix',
        pigeonChannelCodec,
        binaryMessenger: binaryMessenger,
      );
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(
            message != null,
            'Argument for dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onMapFeatureTapped was null.',
          );
          final List<Object?> args = (message as List<Object?>?)!;
          final PlatformMapFeature? arg_feature =
              (args[0] as PlatformMapFeature?);
          assert(
            arg_feature != null,
            'Argument for dev.flutter.pigeon.apple_maps_flutter.AppleMapFlutterApi.onMapFeatureTapped was null, expected non-null PlatformMapFeature.',
          );
          try {
            api.onMapFeatureTapped(arg_feature!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          } catch (e) {
            return wrapResponse(
              error: PlatformException(code: 'error', message: e.toString()),
            );
          }
        });
      }
    }
  }
}
